user_dict = {
    "郑志安": "zhengzhian_zh",
    "黎伟超": "liweichao_zh",
    "林国权": "linguoquan_zh",
    "梁惜家": "liangxijia_zh",
    "冯海": "fenghai_zh",
    "廖飞亮": "liaofeiliang_zh",
    "段金亮": "duanjinliang_zh",
    "黄国印": "huangguoying_zh",
    "梁海明": "lianghaiming_zh",
    "李化武": "lihuawu_zh",
    "李杰": "lijie_zh",
    "刘泽增": "liuzezeng_zh",
    "龙宪彪": "longxianbiao_zh",
    "卢继瑶": "lujiyao_zh",
    "庞智明": "pangzhiming_zh",
    "苏品林": "supinlin_zh",
    "吴华君": "wuhuajun_zh",
    "杨邦淳": "yangbangchun_zh",
    "闫兰松": "yanlansong_zh",
    "曾庆凡": "zengqingfan_zh",
    "赵德成": "zhaodecheng_zh",
}